apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backup/velero/application.yaml
  - monitoring/kube-prometheus-stack/application.yaml
  - monitoring/loki/application.yaml
  - monitoring/crds/application.yaml
  - cilium_infrastructure/cilium/application.yaml
  - loadbalancer/metallb/application.yaml
  - loadbalancer/metallb/IPAddressPool.yaml
  - loadbalancer/metallb/L2Advertisement.yaml
  - storage/local-path/deploy_local_path.yaml
  - test-pod/testing_cilium_ingress_controller/deployment.yaml
  - test-pod/testing_cilium_ingress_controller/service.yaml
  - test-pod/testing_cilium_ingress_controller/ingress.yaml
